DROP TABLE ATTENDEE;
DROP TABLE DELEGATE;
DROP TABLE ORGANIZER;
DROP TABLE SPEAKER;
DROP TABLE SPONSOR;
DROP TABLE COMPANY;
DROP TABLE TIMESLOT;
DROP TABLE LOCATION;
DROP TABLE EVENT;
DROP TABLE LocationAtTimeSlot;
DROP TABLE Interview;
DROP TABLE Workshop;
DROP TABLE Talk;
DROP TABLE Task;
DROP TABLE OrganizerTasks;
DROP TABLE HotelBooking;
DROP TABLE AttendeeHotelBookings;


